#-------------------------------------------------
# This file is generated by the Qt Creator
#-------------------------------------------------

this_dir = $$PWD/../../../..

QT += gui xml

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets serialport

DEFINES += \
    PRO_COMPONENT \
    JWT_LIB \
    ICDCORE_LIB \
    ICDPARSER_LIB \
    ICDCOMM_LIB \
    ICDWORKER_LIB \
    ICDWIDGET_LIB

include($$this_dir/source/common/build.pri)

TARGET = $$qtLibraryTarget(com_channelmgr)

# The .h file which was generated for your project. Feel free to hack it.
HEADERS += \
    $$PWD/comchannelmgr.h \
    $$PWD/comchannelmgrui.h \
    module/comm/commgr_widget.h \
    module/comm/private/commdetail_widget.h \
    module/comm/private/commgr_widget_p.h \
    module/comm/private/file/filedetail_widget.h \
    module/comm/private/file/filesetting_widget.h \
    module/comm/private/serial/serialdetail_widget.h \
    module/comm/private/serial/serialsetting_widget.h \
    module/comm/private/udp/udpdetail_widget.h \
    module/comm/private/udp/udpsetting_widget.h \
    module/comm/private/serial/serialsend_widget.h \
    module/comm/private/serial/serialrecv_widget.h \
    module/comm/private/udp/udpsend_widget.h \
    module/comm/private/udp/udprecv_widget.h \
    module/comm/private/file/filesend_widget.h \
    module/comm/private/file/filerecv_widget.h

# The .cpp file which was generated for your project. Feel free to hack it.
SOURCES += \
    $$PWD/comchannelmgr.cpp \
    $$PWD/comchannelmgrui.cpp \
    module/comm/commgr_widget.cpp \
    module/comm/private/commdetail_widget.cpp \
    module/comm/private/commgr_widget_p.cpp \
    module/comm/private/file/filedetail_widget.cpp \
    module/comm/private/file/filesetting_widget.cpp \
    module/comm/private/serial/serialdetail_widget.cpp \
    module/comm/private/serial/serialsetting_widget.cpp \
    module/comm/private/udp/udpdetail_widget.cpp \
    module/comm/private/udp/udpsetting_widget.cpp \
    module/comm/private/serial/serialsend_widget.cpp \
    module/comm/private/serial/serialrecv_widget.cpp \
    module/comm/private/udp/udpsend_widget.cpp \
    module/comm/private/udp/udprecv_widget.cpp \
    module/comm/private/file/filesend_widget.cpp \
    module/comm/private/file/filerecv_widget.cpp

#
exists($$PWD/com_channelmgr.xml) {
    OTHER_FILES += \
        $$PWD/com_channelmgr.xml
}

#-------------------------------------------------
# resource
#-------------------------------------------------

RESOURCES += \
    resource/resource.qrc

#-------------------------------------------------
# import libraries
#-------------------------------------------------

#-------------------------------------------------
# global commands
#-------------------------------------------------

win32|unix: {
    commands += echo --- console - com_channelmgr --- &

    ## copy files
    dstdir = $$this_dir/component/$$systemdir/com_channelmgr/
    win32:dstdir = $$replace(dstdir, /, \\)
    !exists("$$dstdir"):commands += $(MKDIR) "\"$$dstdir\"" &
    srcfile = $$PWD/com_channelmgr.xml
    win32:srcfile = $$replace(srcfile, /, \\)
    exists("$$srcfile"):commands += $(COPY_FILE) "\"$$srcfile\"" "\"$$dstdir\"" &

    QMAKE_POST_LINK += $$commands
}
